package main

import (
	"os"
	"path"
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
)

const mirrorlist = `################################################################################
	################# Arch Linux mirrorlist generated by Reflector #################
	################################################################################

	# With:       reflector --country Germany --verbose --sort rate --save /etc/pacman.d/mirrorlist
	# When:       2020-01-10 11:51:21 GMT+7
	# From:       https://archlinux.org/mirrors/status/json/
	# Retrieved:  2020-01-10 11:51:21 GMT+7
	# Last Check: 2020-01-10 11:51:21 GMT+7

	Server = http://mirror.sample.ca/archlinux/$repo/os/$arch
	Server = https://a.ab.net/archlinux/$arch/os/$repo
	Server = http://example.tld/repos/$repo/os/$arch#something # Comment
		Server =https://whatever.mirror.server.com/$repo/os/$arch
	Server= http://localhost/mirror/packages/Blackarch/$repo/os/$arch
	Server = https://tooManyTests.com/archlinux/$whatever/os/$arch #Comment
	Server = http://another.test.co.uk/archlinux/$repo/o\$s/$arch
	Server = http://ThisOneShouldNotBeIncluded.test.co.uk/archlinux/
	`

var expectedURLs = []string{
	`http://mirror.sample.ca/archlinux/`,
	`https://a.ab.net/archlinux/`,
	`http://example.tld/repos/`,
	`https://whatever.mirror.server.com/`,
	`http://localhost/mirror/packages/Blackarch/`,
	`https://tooManyTests.com/archlinux/`,
	`http://another.test.co.uk/archlinux/`,
}

func TestParseMirrorlist(t *testing.T) {
	temp := t.TempDir()
	tmpMirrorfile := path.Join(temp, "tmpMirrorFile")

	f, err := os.Create(tmpMirrorfile)
	if err == nil {
		f.Write([]byte(mirrorlist))
		f.Close()
		f, err = os.Open(tmpMirrorfile)
	}
	if err != nil {
		t.Error(err)
	}

	actualURLs, err := parseMirrorlistURLs(f)
	if err != nil {
		t.Error(err)
	}

	if !cmp.Equal(actualURLs, expectedURLs) {
		t.Errorf("Got %v, expected %v", actualURLs, expectedURLs)
	}
}

func TestGetCurrentURLs(t *testing.T) {
	temp := t.TempDir()
	tmpMirrorfile := path.Join(temp, "tmpMirrorFile")

	f, err := os.Create(tmpMirrorfile)
	if err == nil {
		f.Write([]byte(mirrorlist))
		f.Close()
		f, err = os.Open(tmpMirrorfile)
	}

	if err != nil {
		t.Error(err)
	}

	config := parseConfig([]byte(`
cache_dir: ` + temp + `
purge_files_after: 2592000 # 3600 * 24 * 30days
download_timeout: 200
port: 9139
repos:
  archTest:
    mirrorlist: ` + tmpMirrorfile + `

`))
	archTest := config.Repos["archTest"]
	urls := archTest.getUrls()

	if !cmp.Equal(urls, expectedURLs) {
		t.Errorf("Got %v, expected %v", urls, expectedURLs)
	}

	fileInfo, _ := os.Stat(tmpMirrorfile)
	expectedModTime := fileInfo.ModTime()
	gotModTime := archTest.LastModificationTime
	if gotModTime != expectedModTime {
		t.Errorf("Got %v mod time, expected %v mod time", gotModTime, expectedModTime)
	}

	gotCheckTime := archTest.LastMirrorlistCheck
	if time.Since(gotCheckTime) > 3*time.Second {
		t.Errorf("Got %v check time, expected %v check time", gotCheckTime, time.Now())
	}
}
