apiVersion: v1
kind: Service
metadata:
  name: {{ include "pacoloco.fullname" . }}
  labels:
    {{- include "pacoloco.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    #- port: {{ .Values.service.port }} {{ .Values.configuration.address.port }}
    - port: {{ .Values.configuration.address.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pacoloco.selectorLabels" . | nindent 4 }}
